/*
Lab 10: Logical to Physical Address Translation in C

Write a c program to perform logical address to physical address translation. An address generated by the CPU is commonly referred to as a logical address, where as an address seen by the memory unit–that is, the one loaded into the memory-address register of the memory is commonly referred to as the physical address. In essence, logical data refers to an instruction or data in the process address space where as the physical address refers to a main memory location where instruction or data resides.

Physical Address=(Segment×16)+Offset
*/

#include <stdio.h>
#include <stdlib.h>
int main()
{
    int seg, off, logAdd, phyAdd;

    printf("Converting 16-bit Logical Address to 20-Bit Physical Address\n");
    printf("\nEnter 16-bit Segment Value:  ");
    scanf("%x", &seg);
    printf("\nEnter 16-bit Offset Value:  ");
    scanf("%x", &off);

    seg = seg * 16;
    phyAdd = (seg + off);

    printf("\nThe 20-bit Physical Address: %x", phyAdd);

    system("pause");
}